apiVersion: v1
kind: Template
metadata:
  name: fe-app-template
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: fe
    name: fe
  spec:
    runPolicy: Serial
    source:
      git:
        uri: https://github.com/jc-wkshp/frontend
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: nodejs:8
          namespace: openshift
      type: Source
    output:
      to:
        kind: ImageStreamTag
        name: fe:latest
    triggers:
    - type: GitHub
      github:
        secret: jc-wkshp-front-end
    - type: ConfigChange
    - type: ImageChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: fe
    name: fe
  spec:
    replicas: 1
    selector:
      app: fe
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: fe
        name: fe
      spec:
        containers:
        - image: fe:latest
          imagePullPolicy: Always
          name: fe
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            requests:
              cpu: 100m 
              memory: 500Mi 
            limits:
              cpu: 200m 
              memory: 1Gi 
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - fe
        from:
          kind: ImageStreamTag
          name: fe:latest
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: fe
    name: fe
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: fe
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: fe
    name: fe
  spec:
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: fe  
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      app: fe
    name: fe
  spec:
    lookupPolicy:
      local: false
